[package]
name = "subnet_calculator"
version = "1.1.1"
authors = ["Showen"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
arboard = "3.6.1"
dioxus = { version = "0.7.1", features = [] }
dioxus-clipboard = "0.3.0"
dioxus-markdown = "0.0.1"
futures-util = "0.3.31"
gloo-timers = { version = "0.3.0", features = ["futures"] }
ipnet = { version = "2.9", features = ["serde"] }
js-sys = "0.3.83"
ollama-rs = { version = "0.3", features = ["stream"] }
pulldown-cmark = "0.13.0"
rfd = "0.17.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
tokio = "1.48.0"
wasm-bindgen = "0.2.106"
web-sys = { version = "0.3.83", features = [
  "Window",
  "Document",
  "HtmlDocument",
  "HtmlElement",
  "Element",
  "DomTokenList",
  "Storage",
] }


[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
