[application]
name = "Subnet Calculator"
asset_dir = "assets"

[web.resource]
style = ["main.css"]

[bundle]
name = "Subnet Calculator"
identifier = "com.showen.subnetcalculator"
publisher = "Showen"
resources = ["assets/"]
icon = [
  "assets/icon.ico",
  "assets/icon-32.png",
  "assets/icon-128.png",
  "assets/icon-512.png",
  "assets/icon-1024.png"
]
# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
