[application]
name = "subnet-calculator"
asset_dir = "assets"

[web.resource]
style = ["main.css"]

[bundle]
identifier = "com.showen"
publisher = "Showen"
resources = ["assets/"]


# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
